jwt:
  secret-Key: ${JWT_SECRET_KEY}
  access-token-expire-period: 7200      #2시간
  refresh-token-expire-period: 1209600  #2주

Spring:
  Security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

univ:
  api-key: 355b3b71-d255-4f60-bcd5-1ce78406c001jwt
  secret-Key: asdfasdfasdfasdrt123a1241qwetqpknapilugipk1j23k4lhj1adfkj9312kl3nasdkflj9Nvlnyasdfakljf891023jhlkasdf91nkhldf91kjlas90dfjl1k29azalikdjf912kjl3lasd9f0j1kl239asdjlkf
  access-token-expire-period: 7200      #2시간
  refresh-token-expire-period: 1209600  #2주