jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-period: 7200      #2시간
  refresh-token-expire-period: 1209600  #2주

Spring:
  Security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8cea821929f380f4c269a7a1cbb7e5e2
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-secret: FX1qkZtF6MKrxQXEpjbRYkGy1SbeAxO8
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

