spring:
  config:
    import:
      - classpath:application-secret.yml
      - classpath:application-API-KEY.properties
  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.DB_NAME}
    username: ${secrets.DB_USERNAME}
    password: ${secrets.DB_PASSWORD}



  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  profiles:
    include: API-KEY, secret

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB